I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chap2.rpy", line 33, in script
    c__ "ใครเป็นพ่อของสุดสาคร?" with dissolve
Exception: Sayer 'c__' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chap2.rpy", line 33, in script
    c__ "ใครเป็นพ่อของสุดสาคร?" with dissolve
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'c__' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
renpy_framework 1.0
Sun Feb 11 17:03:02 2024
